"""versao_final_com_ids

Revision ID: 2f8e476440bc
Revises: 
Create Date: 2026-03-02 13:46:40.494998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8e476440bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('curso', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=True),
    sa.Column('semestre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('reserva_lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('disciplina', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('horario_fim', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorio.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_lab')
    op.drop_table('usuario')
    op.drop_table('turma')
    op.drop_table('laboratorio')
    # ### end Alembic commands ###
